title: Ryan Huber # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   Seeking a challenging career with a progressive organization that provides an opportunity to capitalize my technical skills and abilities in the field of information technology.
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-huber-749716157/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
