title: Ryan Huber
logo: "/images/logo.jpg?raw=true"
description: 
   Seeking a challenging career with a progressive organization that provides an opportunity to capitalize my technical skills and abilities in the field of information technology.
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-huber-749716157/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
